zds/forum/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

from . import feeds
from . import views


urlpatterns = patterns('',

                       # Feeds
                       url(r'^flux/messages/rss/$', feeds.LastPostsFeedRSS(), name='post-feed-rss'),
                       url(r'^flux/messages/atom/$', feeds.LastPostsFeedATOM(), name='post-feed-atom'),
                       
                       url(r'^flux/sujets/rss/$',
                           feeds.LastTopicsFeedRSS(),
                           name='topic-feed-rss'),
                       url(r'^flux/sujets/atom/$',
                           feeds.LastTopicsFeedATOM(),
                           name='topic-feed-atom'),

                       # Developers warning: if you update something here, check and update help_text
                       # on Category slug field

                       # Home
                       url(r'^$', 'zds.forum.views.index'),

                       # Followed topics
                       url(r'^notifications/$',
                           'zds.forum.views.followed_topics'),

                       # Moderation
                       url(r'^resolution_alerte/$',
                           'zds.forum.views.solve_alert'),

                       # Viewing a thread
                       url(r'^sujet/nouveau/$',
                           'zds.forum.views.new'),
                       url(r'^sujet/editer/$',
                           'zds.forum.views.edit'),
                       url(r'^sujet/deplacer/$',
                           'zds.forum.views.move_topic'),
                       url(r'^sujet/(?P<topic_pk>\d+)/(?P<topic_slug>.+)/$',
                           'zds.forum.views.topic'),
                       url(r'^sujets/membre/(?P<user_pk>\d+)/$',
                           'zds.forum.views.find_topic'),
                       url(r'^sujets/tag/(?P<tag_pk>\d+)/(?P<tag_slug>.+)/$',
                           'zds.forum.views.find_topic_by_tag'),
                       url(r'^sujets/recherche/$',
                           'zds.forum.views.complete_topic'),

                       # Message-related
                       url(r'^message/editer/$',
                           'zds.forum.views.edit_post'),
                       url(r'^message/nouveau/$',
                           'zds.forum.views.answer'),
                       url(r'^message/utile/$',
                           'zds.forum.views.useful_post'),
                       url(r'^message/nonlu/$',
                           'zds.forum.views.unread_post'),
                       url(r'^message/like/$',
                           'zds.forum.views.like_post'),
                       url(r'^message/dislike/$',
                           'zds.forum.views.dislike_post'),
                       url(r'^messages/(?P<user_pk>\d+)/$',
                           'zds.forum.views.find_post'),

                       # Forum details
                       url(r'^(?P<cat_slug>.+)/(?P<forum_slug>.+)/$',
                           'zds.forum.views.details'),

                       # Forums belonging to one category
                       url(r'^(?P<cat_slug>.+)/$',
                           'zds.forum.views.cat_details'),
                       )

zds/urls.py
# encoding: utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap, Sitemap

from zds.article.models import Article
from zds.forum.models import Category, Forum, Topic
from zds.tutorial.models import Tutorial

from . import settings


# SiteMap data
class TutoSitemap(Sitemap):
    changefreq = 'weekly'
    priority = 1

    def items(self):
        return Tutorial.objects.filter(sha_public__isnull=False)

    def lastmod(self, tuto):
        if tuto.update is None:
            return tuto.pubdate
        else:
            return tuto.update

    def location(self, tuto):
        return tuto.get_absolute_url_online()


class ArticleSitemap(Sitemap):
    changefreq = 'weekly'
    priority = 1

    def items(self):
        return Article.objects.filter(sha_public__isnull=False)

    def lastmod(self, article):
        if article.update is None:
            return article.pubdate
        else:
            return article.update

    def location(self, article):
        return article.get_absolute_url_online()

sitemaps = {
    'tutos': TutoSitemap,
    'articles': ArticleSitemap,
    'categories': GenericSitemap(
        {'queryset': Category.objects.all()},
        changefreq='yearly',
        priority=0.7
    ),
    'forums': GenericSitemap(
        {'queryset': Forum.objects.filter(group__isnull=True).exclude(pk=settings.ZDS_APP['forum']['beta_forum_id'])},
        changefreq='yearly',
        priority=0.7
    ),
    'topics': GenericSitemap(
        {'queryset': Topic.objects.filter(is_locked=False,
                                          forum__group__isnull=True).exclude(forum__pk=settings.ZDS_APP['forum']['beta_forum_id']),
         'date_field': 'pubdate'},
        changefreq='hourly',
        priority=0.7
    ),
}


admin.autodiscover()


urlpatterns = patterns('',
                       url(r'^tutoriels/', include('zds.tutorial.urls')),
                       url(r'^articles/', include('zds.article.urls')),
                       url(r'^forums/', include('zds.forum.urls')),
                       url(r'^mp/', include('zds.mp.urls')),
                       url(r'^membres/', include('zds.member.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^pages/', include('zds.pages.urls')),
                       url(r'^galerie/', include('zds.gallery.urls')),
                       url(r'^rechercher/', include('zds.search.urls')),
                       url(r'^munin/', include('zds.munin.urls')),
                       url('', include('social.apps.django_app.urls', namespace='social')),
                       url('', include('django.contrib.auth.urls', namespace='auth')),
                       ('^munin/', include('munin.urls')),

                       url(r'^$', 'zds.pages.views.home'),

                       ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API
urlpatterns += patterns('',
                        url(r'^api/', include('rest_framework_swagger.urls')),
                        url(r'^oauth2/', include('oauth2_provider.urls', namespace='oauth2_provider')),
                        url(r'^api/membres/', include('zds.member.api.urls')),
                        )

# SiteMap URLs
urlpatterns += patterns('django.contrib.sitemaps.views',
                        (r'^sitemap\.xml$',
                         'index',
                         {'sitemaps': sitemaps}),
                        (r'^sitemap-(?P<section>.+)\.xml$',
                            'sitemap',
                            {'sitemaps': sitemaps}),
                        )

if settings.SERVE:
    urlpatterns += patterns('',
                            (r'^static/(?P<path>.*)$',
                             'django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT}),
                            (r'^media/(?P<path>.*)$',
                                'django.views.static.serve',
                                {'document_root': settings.MEDIA_ROOT}),
                            )

# custom view for 500 errors
handler500 = "zds.pages.views.custom_error_500"

zds/forum/models.py
# coding: utf-8

from django.conf import settings
from django.db import models
from zds.utils import slugify
from math import ceil
import os
import string
import uuid

from django.contrib.auth.models import Group, User
from datetime import datetime
from django.core.urlresolvers import reverse
from django.utils.encoding import smart_text

from zds.forum.managers import TopicManager
from zds.utils import get_current_user
from zds.utils.models import Comment, Tag


def sub_tag(g):
    start = g.group('start')
    end = g.group('end')
    return u"{0}".format(start + end)


def image_path_forum(instance, filename):
    """Return path to an image."""
    ext = filename.split('.')[-1]
    filename = u'{}.{}'.format(str(uuid.uuid4()), string.lower(ext))
    return os.path.join('forum/normal', str(instance.pk), filename)


class Category(models.Model):

    """A category, containing forums."""
    class Meta:
        verbose_name = 'Catégorie'
        verbose_name_plural = 'Catégories'

    title = models.CharField('Titre', max_length=80)
    position = models.IntegerField('Position', null=True, blank=True)
    slug = models.SlugField(max_length=80,
                            unique=True,
                            help_text="Ces slugs vont provoquer des conflits "
                            "d'URL et sont donc interdits : notifications "
                            "resolution_alerte sujet sujets message messages")

    def __unicode__(self):
        """Textual form of a category."""
        return self.title

    def get_absolute_url(self):
        return reverse('zds.forum.views.cat_details',
                       kwargs={'cat_slug': self.slug})

    def get_forums(self):
        return Forum.objects.all()\
            .filter(category=self)\
            .order_by('position_in_category')


class Forum(models.Model):

    """A forum, containing topics."""
    class Meta:
        verbose_name = 'Forum'
        verbose_name_plural = 'Forums'

    title = models.CharField('Titre', max_length=80)
    subtitle = models.CharField('Sous-titre', max_length=200)

    group = models.ManyToManyField(
        Group,
        verbose_name='Groupe autorisés (Aucun = public)',
        null=True,
        blank=True)
    image = models.ImageField(upload_to=image_path_forum)

    category = models.ForeignKey(Category, db_index=True, verbose_name='Catégorie')
    position_in_category = models.IntegerField('Position dans la catégorie',
                                               null=True, blank=True, db_index=True)

    slug = models.SlugField(max_length=80, unique=True)

    def __unicode__(self):
        """Textual form of a forum."""
        return self.title

    def get_absolute_url(self):
        return reverse('zds.forum.views.details',
                       kwargs={'cat_slug': self.category.slug,
                               'forum_slug': self.slug})

    def get_topic_count(self):
        """Gets the number of threads in the forum."""
        return Topic.objects.all().filter(forum__pk=self.pk).count()

    def get_post_count(self):
        """Gets the number of posts for a forum."""
        return Post.objects.filter(topic__forum=self).count()

    def get_last_message(self):
        """Gets the last message on the forum, if there are any."""
        try:
            return Post.objects.all().filter(topic__forum__pk=self.pk).order_by('-pubdate')[0]
        except IndexError:
            return None

    def can_read(self, user):
        """Checks if the forum can be read by the user."""

        if self.group.count() == 0:
            return True
        else:
            if user.is_authenticated():
                groups = Group.objects.filter(user=user).all()
                return Forum.objects.filter(
                    group__in=groups,
                    pk=self.pk).exists()
            else:
                return False


class Topic(models.Model):

    """A thread, containing posts."""
    class Meta:
        verbose_name = 'Sujet'
        verbose_name_plural = 'Sujets'

    title = models.CharField('Titre', max_length=80)
    subtitle = models.CharField('Sous-titre', max_length=200)

    forum = models.ForeignKey(Forum, verbose_name='Forum', db_index=True)
    author = models.ForeignKey(User, verbose_name='Auteur',
                               related_name='topics', db_index=True)
    last_message = models.ForeignKey('Post', null=True,
                                     related_name='last_message',
                                     verbose_name='Dernier message')
    pubdate = models.DateTimeField('Date de création', auto_now_add=True)

    is_solved = models.BooleanField('Est résolu', default=False, db_index=True)
    is_locked = models.BooleanField('Est verrouillé', default=False)
    is_sticky = models.BooleanField('Est en post-it', default=False, db_index=True)

    tags = models.ManyToManyField(
        Tag,
        verbose_name='Tags du forum',
        null=True,
        blank=True,
        db_index=True)

    key = models.IntegerField('cle', null=True, blank=True)

    objects = TopicManager()

    def __unicode__(self):
        """Textual form of a thread."""
        return self.title

    def get_absolute_url(self):
        return reverse(
            'zds.forum.views.topic',
            args=[self.pk, slugify(self.title)]
        )

    def get_post_count(self):
        """Return the number of posts in the topic."""
        return Post.objects.filter(topic__pk=self.pk).count()

    def get_last_post(self):
        """Gets the last post in the thread."""
        return Post.objects.select_related("author__profile").get(pk=self.last_message)

    def get_last_answer(self):
        """Gets the last answer in the thread, if any."""
        last_post = self.get_last_post()

        if last_post == self.first_post():
            return None
        else:
            return last_post

    def first_post(self):
        """Return the first post of a topic, written by topic's author."""
        return Post.objects\
            .filter(topic=self)\
            .select_related("author")\
            .order_by('position')\
            .first()

    def add_tags(self, tag_collection):
        for tag in tag_collection:
            tag_title = smart_text(tag.strip().lower())
            current_tag = Tag.objects.filter(title=tag_title).first()
            if current_tag is None:
                current_tag = Tag(title=tag_title)
                current_tag.save()

            self.tags.add(current_tag)
        self.save()

    def get_followers_by_email(self):
        """Return set on followers by email"""
        return TopicFollowed.objects.filter(topic=self, email=True).select_related("user")

    def last_read_post(self):
        """Return the last post the user has read."""
        try:
            return TopicRead.objects\
                .select_related()\
                .filter(topic=self, user=get_current_user())\
                .latest('post__position').post
        except:
            return self.first_post()

    def first_unread_post(self):
        """Return the first post the user has unread."""
        try:
            last_post = TopicRead.objects\
                .filter(topic=self, user=get_current_user())\
                .latest('post__position').post

            next_post = Post.objects.filter(
                topic__pk=self.pk,
                position__gt=last_post.position)\
                .select_related("author").first()
            return next_post
        except:
            return self.first_post()

    def is_followed(self, user=None):
        """Check if the topic is currently followed by the user.

        This method uses the TopicFollowed objects.

        """
        if user is None:
            user = get_current_user()

        return TopicFollowed.objects.filter(topic=self, user=user).exists()

    def is_email_followed(self, user=None):
        """Check if the topic is currently email followed by the user.

        This method uses the TopicFollowed objects.

        """
        if user is None:
            user = get_current_user()

        try:
            TopicFollowed.objects.get(topic=self, user=user, email=True)
        except TopicFollowed.DoesNotExist:
            return False
        return True

    def antispam(self, user=None):
        """Check if the user is allowed to post in a topic according to the
        SPAM_LIMIT_SECONDS value.

        If user shouldn't be able to post, then antispam is activated
        and this method returns True. Otherwise time elapsed between
        user's last post and now is enough, and the method will return
        False.

        """
        if user is None:
            user = get_current_user()

        last_user_post = Post.objects\
            .filter(topic=self)\
            .filter(author=user.pk)\
            .order_by('position')\
            .last()

        if last_user_post and last_user_post == self.get_last_post():
            t = datetime.now() - last_user_post.pubdate
            if t.total_seconds() < settings.ZDS_APP['forum']['spam_limit_seconds']:
                return True

        return False

    def never_read(self):
        return never_read(self)


class Post(Comment):

    """A forum post written by an user."""

    topic = models.ForeignKey(Topic, verbose_name='Sujet', db_index=True)

    is_useful = models.BooleanField('Est utile', default=False)

    def __unicode__(self):
        """Textual form of a post."""
        return u'<Post pour "{0}", #{1}>'.format(self.topic, self.pk)

    def get_absolute_url(self):
        page = int(ceil(float(self.position) / settings.ZDS_APP['forum']['posts_per_page']))

        return '{0}?page={1}#p{2}'.format(
            self.topic.get_absolute_url(),
            page,
            self.pk)


class TopicRead(models.Model):

    """Small model which keeps track of the user viewing topics.

templates/forum/topic/followed.html
{% extends "forum/base.html" %}
{% load i18n %}


{% block title %}
    {% trans "Sujets suivis" %}
{% endblock %}



{% block breadcrumb %}
    <li>{% trans "Sujets suivis" %}</li>
{% endblock %}



{% block headline %}
    {% trans "Sujets suivis" %}
{% endblock %}



{% block content %}
    {% include "misc/pagination.part.html" with position="top" %}

	<div class="topic-list navigable-list">
	    {% for topic in followed_topics %}
	        {% include "forum/includes/topic_row.part.html" %}
	    {% endfor %}
    </div>
    
    {% include "misc/pagination.part.html" with position="bottom" %}
{% endblock %}

templates/forum/topic/index.html
{% extends "forum/base.html" %}
{% load emarkdown %}
{% load captureas %}
{% load set %}
{% load profile %}
{% load crispy_forms_tags %}
{% load i18n %}



{% block title %}
    {% if topic.is_solved %}[{% trans "Résolu" %}]{% endif %} {{ topic.title }}
{% endblock %}

{% block breadcrumb %}
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
        <a href="{{ topic.forum.category.get_absolute_url }}" itemprop="url">
            <span itemprop="title">{{ topic.forum.category.title }}</span>
        </a>
    </li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
        <a href="{{ topic.forum.get_absolute_url }}" itemprop="url">
            <span itemprop="title">{{ topic.forum.title }}</span>
        </a>
    </li>
    <li>
        {{ topic.title }}
    </li>
{% endblock %}



{% block schema %}
    itemscope itemtype="http://schema.org/Question"
{% endblock %}



{% block headline %}
    {{ topic.title }}
{% endblock %}



{% block headline_sub %}
    {{ topic.subtitle }}
{% endblock %}



{% block content %}
    {% if topic.tags.all %}
        <ul class="taglist" itemprop="keywords">
            {% for tag in topic.tags.all %}
                <li>
                    <a href="{% url "zds.forum.views.find_topic_by_tag" tag.pk tag.slug %}">
                        {{ tag.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    {% include "misc/pagination.part.html" with position="top" %}

        <div 
            class="alert-box success ico-after tick light {% if not topic.is_solved %}empty{% endif %}"
            data-ajax-output="solve-topic"
        >
            {% trans "L'auteur de ce sujet a trouvé une solution à son problème" %}.
        </div>
    

    {% for message in posts %}
        {% captureas edit_link %}
            {% url "zds.forum.views.edit_post" %}?message={{ message.pk }}
        {% endcaptureas %}

        {% captureas cite_link %}
            {% url "zds.forum.views.answer" %}?sujet={{ topic.pk }}&amp;cite={{ message.pk }}
        {% endcaptureas %}

        {% captureas helpful_link %}
            {% url "zds.forum.views.useful_post" %}?message={{ message.pk }}
        {% endcaptureas %}

        {% captureas upvote_link %}
            {% url "zds.forum.views.like_post" %}?message={{ message.pk }}
        {% endcaptureas %}

        {% captureas downvote_link %}
            {% url "zds.forum.views.dislike_post" %}?message={{ message.pk }}
        {% endcaptureas %}

        {% captureas alert_solve_link %}
            {% url "zds.forum.views.solve_alert" %}
        {% endcaptureas %}

        {% captureas unread_link %}
            {% url "zds.forum.views.unread_post" %}?message={{ message.pk }}
        {% endcaptureas %}

        {% if forloop.first and nb > 1 %}
            {% set True as is_repeated_message %}
        {% else %}
            {% set False as is_repeated_message %}
        {% endif %}

        {% if forloop.first and nb = 1 %}
            {% set False as answer_schema %}
        {% else %}
            {% set True as answer_schema %}
        {% endif %}

        {% include "misc/message.part.html" with perms_change=perms.forum.change_topic answer_schema=answer_schema can_unread=True unread_link=unread_link %}
    {% endfor %}

    {% include "misc/pagination.part.html" with position="bottom" %}


    {# Anwser form #}
    {% captureas form_action %}
        {% url "zds.forum.views.answer" %}?sujet={{ topic.pk }}
    {% endcaptureas %}

    {% include "misc/message_form.html" with member=user %}
{% endblock %}



{% block new_btn %}
    <a href="{% url "zds.forum.views.new" %}?forum={{ topic.forum.pk }}" class="new-btn ico-after more blue">
        {% trans "Nouveau sujet" %}
    </a>
{% endblock %}



{% block sidebar_actions %}
    {% if topic.author.pk == user.pk or perms.forum.change_topic %}
        <li>
            <form action="{% url "zds.forum.views.edit" %}" method="post">
                <input type="hidden" name="topic" value="{{ topic.pk }}">
                <input type="hidden" name="nb" value="{{ nb }}">
                <input type="hidden" name="page" value="{{ nb }}">
                <input type="hidden" name="solved" value="1">
                {% csrf_token %}

                <button
                    class="ico-after tick {% if topic.is_solved %}blue{% else %}green{% endif %}"
                    type="submit" data-ajax-input="solve-topic"
                    data-content-on-click="
                        {% if topic.is_solved %}
                            {% trans "Marquer comme résolu" %}
                        {% else %}
                            {% trans "Marquer comme non résolu" %}
                        {% endif %}
                    "
                >
                    {% if topic.is_solved %}
                        {% trans "Marquer comme non résolu" %}
                    {% else %}
                        {% trans "Marquer comme résolu" %}
                    {% endif %}
                </button>
            </form>
        </li>
    {% endif %}

    <li>
        <form action="{% url "zds.forum.views.edit" %}" method="post">
            <input type="hidden" name="topic" value="{{ topic.pk }}">
            <input type="hidden" name="nb" value="{{ nb }}">
            <input type="hidden" name="page" value="{{ nb }}">
            <input type="hidden" name="follow" value="1">
            {% csrf_token %}

            <button
                class="follow ico-after star {% if topic.is_followed %}yellow{% else %}blue{% endif %}"
                type="submit" data-ajax-input="follow-topic"
                data-content-on-click="
                    {% if topic.is_followed %}
                        {% trans "Suivre ce sujet" %}
                    {% else %}
                        {% trans "Ne plus suivre ce sujet" %}
                    {% endif %}
                "
            >
                {% if topic.is_followed %}
                    {% trans "Ne plus suivre ce sujet" %}
                {% else %}
                    {% trans "Suivre ce sujet" %}
                {% endif %}
            </button>
        </form>
    </li>
    <li>
        <form action="{% url "zds.forum.views.edit" %}" method="post">
            <input type="hidden" name="topic" value="{{ topic.pk }}">
            <input type="hidden" name="nb" value="{{ nb }}">
            <input type="hidden" name="page" value="{{ nb }}">
            <input type="hidden" name="email" value="1">
            {% csrf_token %}

            <button
                class="email ico-after {% if not topic.is_email_followed %}blue{% endif %}"
                type="submit" data-ajax-input="follow-topic-by-email"
                data-content-on-click="
                    {% if topic.is_email_followed %}
                        {% trans "Être notifié par courriel" %}
                    {% else %}
                        {% trans "Ne plus être notifié par courriel" %}
                    {% endif %}
                "
            >
                {% if topic.is_email_followed %}
                    {% trans "Ne plus être notifié par courriel" %}
                {% else %}
                    {% trans "Être notifié par courriel" %}
                {% endif %}
            </button>
        </form>
    </li>
{% endblock %}



{% block sidebar_blocks %}
    {% if perms.forum.change_topic %}
        <div class="mobile-menu-bloc mobile-all-links mobile-show-ico" data-title="Modération">
            <h3>{% trans "Modération" %}</h3>
            <ul>
                <li>
                    <a href="#lock-open-topic-{{ topic.pk }}" class="open-modal ico-after lock {% if not topic.is_locked %}blue{% endif %}">
                        {% if topic.is_locked %}
                            {% trans "Ouvrir le sujet" %}
                        {% else %}
                            {% trans "Fermer le sujet" %}
                        {% endif %}
                    </a>
                    <form action="{% url "zds.forum.views.edit" %}" method="post" id="lock-open-topic-{{ topic.pk }}" class="modal modal-small">
                        <input type="hidden" name="topic" value="{{ topic.pk }}">
                        <input type="hidden" name="nb" value="{{ nb }}">
                        <input type="hidden" name="page" value="{{ nb }}">
                        <input type="hidden" name="lock" value="{% if topic.is_locked %}false{% else %}true{% endif %}">
            			{% csrf_token %}

                        <p>
                            {% trans "Voulez-vous confirmer" %}
                                <em>
                                    {% if topic.is_locked %}
                                        {% trans "la réouverture" %}
                                    {% else %}
                                        {% trans "la fermeture" %}
                                    {% endif %}
                                </em>
                            {% trans "du sujet ?" %}
                        </p>

                        <button type="submit" name="lock-open-topic-{{ topic.pk }}">
                            {% trans "Confirmer" %}
                        </button>
                    </form>
                </li>

                <li>
                    <form action="{% url "zds.forum.views.edit" %}" method="post">
                        <input type="hidden" name="topic" value="{{ topic.pk }}">
                        <input type="hidden" name="nb" value="{{ nb }}">
                        <input type="hidden" name="page" value="{{ nb }}">
                        <input type="hidden" name="sticky" value="{% if topic.is_sticky %}false{% else %}true{% endif %}">
            			{% csrf_token %}

                        <button class="ico-after pin {% if not topic.is_sticky %}blue{% endif %}" type="submit">
                            {% if topic.is_sticky %}
                                {% trans "Enlever du post-it" %}
                            {% else %}
                                {% trans "Marquer en post-it" %}
                            {% endif %}
                        </button>
                    </form>
                </li>

                <li>
                    <a href="#move-topic" class="ico-after arrow-right blue open-modal">{% trans "Déplacer le sujet" %}</a>
                    <div class="modal modal-small" id="move-topic">
                        {% crispy form_move %}
                    </div>
                </li>
            </ul>
        </div>
    {% endif %}
{% endblock %}

templates/forum/topic/new.html
{% extends "forum/base.html" %}
{% load emarkdown %}
{% load crispy_forms_tags %}
{% load i18n %}



{% block title %}
    {% trans "Nouveau sujet" %}
{% endblock %}



{% block headline %}
    {% trans "Nouveau sujet" %}
{% endblock %}



{% block breadcrumb %}
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
        <a href="{{ forum.category.get_absolute_url }}" itemprop="url">
            <span itemprop="title">{{ forum.category.title }}</span>
        </a>
    </li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
        <a href="{{ forum.get_absolute_url }}" itemprop="url">
            <span itemprop="title">{{ forum.title }}</span>
        </a>
    </li>
    <li>{% trans "Nouveau sujet" %}</li>
{% endblock %}



{% block content %}
	<div data-solved-topics-url="{% url "zds.forum.views.complete_topic" %}">
   		{% crispy form %}
    </div>

    {% if text %}
        {% include "misc/previsualization.part.html" %}
    {% endif %}
{% endblock %}